name: Build Vue
on: 
  push:
    branches:
    - dev
  pull_request:
    branches:
    - dev
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v3
    - name: Vue to Github Pages
      uses: LizAinslie/VueBuildToBranchAction@1.0.2+1
      with:
        username: PowerCreationD
        reponame: Kohaku
        token: ${{ secrets.ACCESS_TOKEN }}
        gitemail: powercreationd@gmail.com
        gitname: Power Creation
        gitmsg: deploy the dev environment to Github page
        gitbranch: gh-pages
        useyarn: false
